export const type = {
  FETCH_USER:'FETCH_USER',
  CREATE_PROFILE: 'CREATE_PROFILE',
  STORE_IMAGE: 'STORE_IMAGE',
  FETCH_EVENT: 'FETCH_EVENT',
  FETCH_ALL_EVENTS: 'FETCH_ALL_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  CREATE_GROUP: 'CREATE_GROUP'
}